// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GoToDnSpy
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidGoToDnSpyPackageString = "c827298b-8d81-47c0-bed9-cdf072e68d4f";
        public static Guid guidGoToDnSpyPackage = new Guid(guidGoToDnSpyPackageString);

        public const string guidGoToDnSpyPackageCmdSetMenuString = "4843d15e-dca8-4935-8ba3-66c4d25fb295";
        public static Guid guidGoToDnSpyPackageCmdSetMenu = new Guid(guidGoToDnSpyPackageCmdSetMenuString);

        public const string guidImagesString = "36462768-caed-442f-be73-841d637c2e3b";
        public static Guid guidImages = new Guid(guidImagesString);

        public const string guidGoToDnSpyPackageCmdSetContextMenuString = "d5d8efc6-dc17-4229-9088-dddf76ac0ab3";
        public static Guid guidGoToDnSpyPackageCmdSetContextMenu = new Guid(guidGoToDnSpyPackageCmdSetContextMenuString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int GoToDnSpyId = 0x0100;
        public const int ico = 0x0001;
        public const int EditorContextMenuGroup = 0x3020;
        public const int GoToDnSpyContextMenuId = 0x4020;
    }
}