// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GoToDnSpy
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidGoToDnSpyPackageString = "c827298b-8d81-47c0-bed9-cdf072e68d4f";
        public const string guidGoToDnSpyPackageCmdSetString = "4843d15e-dca8-4935-8ba3-66c4d25fb295";
        public const string guidImagesString = "36462768-caed-442f-be73-841d637c2e3b";
        public static Guid guidGoToDnSpyPackage = new Guid(guidGoToDnSpyPackageString);
        public static Guid guidGoToDnSpyPackageCmdSet = new Guid(guidGoToDnSpyPackageCmdSetString);
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int GoToDnSpyId = 0x0100;
        public const int ico = 0x0001;
    }
}
