// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GoToDnSpy
{
    internal sealed partial class Vsix
    {
        public const string Id = "GoToDnSpy";
        public const string Name = "GoToDnSpy";
        public const string Description = @"Open dnSpy or source.dot.net and select method or type under caret.";
        public const string Language = "en-US";
        public const string Version = "1.1.3";
        public const string Author = "Vladimir Chirikov";
        public const string Tags = "GoToDnSpy, GoTo, Disasm, ILSpy, ILDisasm, Disassemble, CIL, IL, MSIL, dnSpy, de4dot, dnlib, decompile, Emit";
    }
}
