// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GoToDnSpy
{
    static class Vsix
    {
        public const string Id = "GoToDnSpy";
        public const string Name = "GoToDnSpy";
        public const string Description = @"Open dnSpy and select method or type under caret.";
        public const string Language = "en-US";
        public const string Version = "1.0.8";
        public const string Author = "Vladimir Chirikov";
        public const string Tags = "GoToDnSpy, GoTo, Disasm, ILSpy, ILDisasm, Disassemble, CIL, IL, MSIL, dnSpy, de4dot, dnlib, decompile, Emit";
    }
}
